/*
* Configuration of module: Det (Det_Cfg.h)
*
* Created by:              
* Copyright:               
*
* Configured for (MCU):    STM32_F107
*
* Module vendor:           ArcCore
* Generator version:       2.0.1
*
* Generated by Arctic Studio (http://arccore.com) 
*/


#if !(((DET_SW_MAJOR_VERSION == 1) && (DET_SW_MINOR_VERSION == 0)) )
#error Det: Configuration file expected BSW module version to be 1.0.*
#endif

/*
 * Development Error Tracer driver
 *
 * Specification: Autosar v2.0.1, Final
 *
 */
#ifndef DET_CFG_H
#define DET_CFG_H 

#include <stdint.h>

// #define DET_ENABLE_CALLBACKS STD_ON // Enable to use callback on errors
// #define DET_USE_RAMLOG       STD_ON  // Enable to log DET errors to ramlog
// #define DET_WRAP_RAMLOG      STD_ON  // The ramlog wraps around when reaching the end
// #define DET_USE_STDERR       STD_ON // Enable to get DET errors on stderr
// #define DET_DEINIT_API       STD_ON // Enable/Disable the Det_DeInit function
// #define DET_RAMLOG_SIZE         (16)  // Number of entries in ramlog
// #define DET_NUMBER_OF_CALLBACKS (5)  // Number of callbacks

bool DET_ENABLE_CALLBACKS = true; // Enable to use callback on errors
bool DET_USE_RAMLOG = true;  // Enable to log DET errors to ramlog
bool DET_WRAP_RAMLOG = true;  // The ramlog wraps around when reaching the end
bool DET_USE_STDERR = true; // Enable to get DET errors on stderr
bool DET_DEINIT_API = true; // Enable/Disable the Det_DeInit function
uint8_t DET_RAMLOG_SIZE = 16;  // Number of entries in ramlog
uint8_t DET_NUMBER_OF_CALLBACKS = 5;  // Number of callbacks

#endif /* DET_CFG_H */
